### ISSUE TITLE
require() no longer works?

### ISSUE THREAD

**Issue by CodeOtter** [nikku/karma-browserify#104]
**Test 1**
```
// test.js
var a = require('./someFile');
describe(...);

// someFile.js
module.exports = 'hello';
```

Error:
```
PhantomJS 1.9.8 (Linux) ERROR
  Error: Cannot find module './someFile'
  at /tmp/39f6e29b8a6217a76e276a5f462db820db2cd81f.browserify:1:0 <- node_modules/karma-browserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:0
```

**Test 2**
```
// test.js
var a = require('./someFile.js');
describe(...);

// someFile.js
module.exports = 'hello';
```

Error:
```
PhantomJS 1.9.8 (Linux) ERROR
  Error: Cannot find module './someFile.js'
  at /tmp/39f6e29b8a6217a76e276a5f462db820db2cd81f.browserify:1:0 <- node_modules/karma-browserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:0
```

**Test 3**
```
// test.js
var a = require('util');
describe(...);
```

Error:
```
PhantomJS 1.9.8 (Linux) ERROR
  Error: Cannot find module 'util'
  at /tmp/39f6e29b8a6217a76e276a5f462db820db2cd81f.browserify:1:0 <- node_modules/karma-browserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:0
```
No idea why this is happening.  Both files are in the same directory.  For whatever reason, require no longer seems able to navigate to any path or file anywhere in a file tree.  It doesn't even work for node modules that browserify bundles up...

I am at a total loss o___O

**Comment by bendrucker** [comment]
We're going to need you to reproduce your environment or at very least copy and paste your config to have any insight into what's wrong here.

**Comment by CodeOtter** [comment]
```javascript
// karma.conf.js
// Karma configuration
// Generated on Tue Dec 02 2014 12:52:50 GMT-0800 (PST)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    captureTimeout: 100000,

    browserNoActivityTimeout: 100000,

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['browserify', 'jasmine', 'benchmark'],

    //browserNoActivityTimeout: 100000,

    // list of files / patterns to load in the browser
    files: [
      'tests/Phantom-shim.js',
      'tests/**/*Test.js*',
      'src/components/*/tests/**/*Test.js*',
      'src/framework/tests/**/*Test.js*',
      'src/photon/tests/**/*Test.js*'
    ],

    // list of files to exclude
    exclude: [],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'tests/**/*Test.js*': ['browserify'],
      'src/components/*/tests/**/*Test.js*': ['browserify'],
      'src/framework/tests/**/*Test.js*': ['browserify'],
      'src/**/*.js*': ['coverage', 'complexity']
    },

    coverageReporter: {
        type: 'html',
        dir: 'reports/coverage/'
    },

    complexityConfig: {
        dir: 'reports/complexity',
        forin: true,
        trycatch: true,
        newmi: true
    },

    browserify: {
        transform: [['reactify', { harmony: true }]],
        extensions: ['.jsx'],
        debug: true
    },

    // test results reporter to use
    reporters: ['clear-screen', 'progress', 'coverage', 'notify'], // karma-benchmark

    notifyReporter: {
        reportEachFailure: true,
        reportSuccess: true
    },

    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [/*'Chrome', */'PhantomJS'/*, 'Firefox', 'Safari', 'IE'*/],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
};
```

When ```require('util')``` is ran in the ```src/photon``` directory, it throws the error.  When it is ran anywhere else, there is no error.

**Comment by CodeOtter** [comment]
damn it, forgot file patterns have to be in the preprocessor... doh.. thanks!

**Comment by bendrucker** [comment]
:+1:! Also, you can't use karma preprocessors to cover your code here. 

https://github.com/devongovett/browserify-istanbul
