### ISSUE TITLE
SourceMap position not found for trace: TypeError: ...

### ISSUE THREAD

**Issue by svi3c** [nikku/karma-browserify#184]
Hello,

I've got the following karma configuration:

``` coffee-script
module.exports = (config) ->
  config.set
    frameworks: ["browserify", "jasmine"]
    files: [
      "node_modules/angular/angular.js"
      "node_modules/angular-mocks/angular-mocks.js"
      "app/**/*.spec.js"
    ]
    preprocessors:
      "app/**/*.js": ["browserify"]
    browserify:
      debug: true
      configure: (bundle) ->
        bundle.once "prebundle", ->
          bundle.transform "babelify"
    reporters: ["dots"]
    port: 8877
    colors: true
    logLevel: config.LOG_INFO
    autoWatch: false
    browsers: ["PhantomJS"]
    singleRun: true
```

When I get an error, the stack trace cannot be linked with the source maps:

```
SourceMap position not found for trace: TypeError: undefined is not an object (evaluating '[...]') in http://localhost:8877/absolute/tmp/c6ec59ad61f294fd51d07305eeaf5c17.browserify?ed7e1e8ce42e802c4d614ba337bf1dc8ac6e27b9 (line 182)
```

Any Idea what's going wrong here?

**Comment by bendrucker** [comment]
Can we get some code please?

**Comment by svi3c** [comment]
Sure!
The problem is that the issue occurs in a closed source project.
I'll boil it down to the essentials when I've got time.

**Comment by hazboun** [comment]
I believe I have the same error testing React. my karma.conf.js looks like this:

```
module.exports = function(config) {

  config.set({

    basePath: ".",

    frameworks: ['jasmine', 'browserify'],

    preprocessors: {

      'tests/**/*.js': ['babel', 'browserify']

    },

    babelPreprocessor:{

        options: {

          presets: ['es2015'],

          sourceMap: 'inline'

        }
    },

    browserify: {
      debug: true,

      transform: [ 'babelify'],

      configure: function(bundle){

        bundle.on("prebundle", function(){ 

          bundle.external("react/addons");

          bundle.external("react/lib/ReactContext");

          bundle.external("react/lib/ExecutionEnvironment");

        });

      }

    },

    reporters: ['spec'],

    colors: true,

    logLevel: config.LOG_INFO,

    autoWatch: true,

    browsers: ['PhantomJS'],

    files: [

      'tests/**/*.js'

    ]

  });

};
```

My one and only test file has:
```
'use strict';

import React from 'react';
import {mount} from 'enzyme';
import sinon from 'sinon';
import Footer from '../src/js/components/Footer';

describe('<Footer/>', () => {
	
	it('renders footer <Footer/> component', () => {
		const wrapper = mount(<Footer/>);
		console.log(wrapper);
		expect(wrapper.find('.app_footer')).to.have.length(1);
	});
});
```

Footer component has only one div with class name '.app_footer'. The error I get is this:

```
SourceMap position not found for trace: TypeError: undefined is not an object (evaluating 'expect(wrapper.find('.app_wrapper')).to.have') in http://localhost:9876/absolute/var/folders/wr/hkjbf_wd3tnf5j9t2p8ndnt40000gn/T/40f5d6b577f0f7e57a2eb4aabc9edf46.browserify?d01138ff9d27c662c126752a88873bdf74683625 (line 61603)
http://localhost:9876/absolute/var/folders/wr/hkjbf_wd3tnf5j9t2p8ndnt40000gn/T/40f5d6b577f0f7e57a2eb4aabc9edf46.browserify?d01138ff9d27c662c126752a88873bdf74683625:61603:42
```

**Comment by nikku** [comment]
@hazboun Can you provide us with a sample project that reproduces the issue?

**Comment by hazboun** [comment]
[Sample.zip](https://github.com/nikku/karma-browserify/files/288503/Sample.zip)
This is my sample project. Btw, I only that error when the test fails.

**Comment by leyayun** [comment]
I got the same error.

**Comment by bendrucker** [comment]
Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to say "me too" instead of notifying everyone on a thread

**Comment by SpainTrain** [comment]
This may not be specific to karma-browserify - I am using karma-webpack and am experiencing the same behavior.

**Comment by nikku** [comment]
That is what I thought, too. Did you find an upstream bug in TypeScript or a sourcemap library?

**Comment by SpainTrain** [comment]
I have not tracked down the root cause in an upstream yet, but I am not using typescript, so that eliminates that possibility =-D

**Comment by nottinhill** [comment]
I have Typescript too and same error.

**Comment by web2style** [comment]
Any update on this?

**Comment by fknop** [comment]
I just had the same issue with Typescript `2.2.x`. I reverted to version `2.0.8` and the issue was fixed.

**Comment by ChrisGibb** [comment]
This is a bit random. But I had this issue. When I deleted a line that just has a ; on it the error disappeared.

I'm using typescript.

**Comment by nikku** [comment]
As indicated in the comments, this seems to be a TypeScript source map generation.

**Comment by ryanki1** [comment]
Can also happen if one of your typescript files has a compile error - in my case it was one of my test files as referenced by the error:

**02 06 2017 15:16:54.630:WARN [reporter]: SourceMap position not found for trace:
 undefined
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  {
    "line": 104034,
    "sourceURL": "src/test.ts",
    ....**

**Comment by MattWilliamsDev** [comment]
I'm not using typescript and get this error. just regular `source-map`.

**Comment by petrind** [comment]
I encountered this issue, and it turned out it is because I didn't use correct mode for webpack config in `karma.conf.js`

Solution
karma.conf.js
```
webpack: {
      mode: 'development',
```

version
```
"karma-sourcemap-loader": "^0.3.7",
"karma-webpack": "^4.0.2",
```

**Comment by septagram** [comment]
If you are using `karma-sourcemap-loader`, try switching to [`karma-source-map-support`](https://www.npmjs.com/package/karma-source-map-support).

My case: Babel, no TypeScript, Webpack and not Browserify, I was using `karma-sourcemap-loader`.

- When throwing errors or failing assertions in test, there would be anywhere from 2 to 12 "SourceMap position not found for trace" warnings *for each thrown error*, badly polluting the output. The errors themselves though were displayed correctly, source maps working.
- When using `console.error()` to print stack traces without halting execution, there would be the same "SourceMap position not found for trace" noise, but console output for errors would not be mapped, line numbers referencing compiled bundles, not original sources.

After switching, both use cases work perfectly fine, outputting mapped stack traces, no extra warnings.

This is likely not to be relevant to the OP's problem, but this issue comes up as the Google's top hit for "SourceMap position not found for trace", so I hope that'll help someone.

**Comment by thekevinscott** [comment]
I'm also running into this issue, and unfortunately @septagram's solution doesn't work for me.

My `karma.config.js`:

```
module.exports = function(config) {
  config.set({
    frameworks: ["mocha", "karma-typescript"],
    files: [
      "src/**/*.ts"
    ],
    preprocessors: {
      "**/*.ts": "karma-typescript"
    },
    karmaTypescriptConfig: {
      include: ["src/**/*.ts"],
      tsconfig: './test-tsconfig.json',
    },
    reporters: ["progress", "karma-typescript"],
    browsers: ['ChromeHeadless'],
  });
};
```

And `test-tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "skipLibCheck": true,
    "strictNullChecks": false,
    "strict": true,
    "sourceMap": true,
    "moduleResolution": "node"
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}
```

Gives me:

```
Chrome Headless 84.0.4147.105 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
03 08 2020 12:07:52.113:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.113:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.113:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.113:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.114:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.114:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.114:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
    at Context.<anonymous> (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:41:57)
03 08 2020 12:07:52.114:WARN [reporter]: SourceMap position not found for trace: AssertionError: expected 'a' to equal
'b'
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:43:35
    at step (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:33:23)
    at Object.next (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:14:53)
    at http://localhost:9876/base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:8:71
    at new Promise (<anonymous>)
    at __awaiter (base/src/upscale.test.js?20df1025977bd3ae048a1ea3861f34519dc74a99:4:12)
Chrome Headless 84.0.4147.105 (Linux x86_64) predict should make a prediction FAILED
        AssertionError: expected 'a' to equal 'b'
            at src/upscale.test.ts:7:20 <- src/upscale.test.js:43:35
            at step (src/upscale.test.js:33:23)
            at Object.next (src/upscale.test.js:14:53)
            at src/upscale.test.js:8:71
            at new Promise (<anonymous>)
            at __awaiter (src/upscale.test.js:4:12)
            at Context.<anonymous> (src/upscale.test.ts:6:34 <- src/upscale.test.js:41:57)
Chrome Headless 84.0.4147.105 (Linux x86_64): Executed 1 of 1 (1 FAILED) (0.01 secs / 0.001 secs)
TOTAL: 1 FAILED, 0 SUCCESS
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Attached is the log output when running with `DEBUG`.

[log.txt](https://github.com/nikku/karma-browserify/files/5017053/log.txt)
